on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *" ## at 00:00 everyday

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: |
          cd Tracker
          python compile.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
